name: Deploy do Site da RR Engenharia

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências e fazer o Build
        run: |
          npm install
          npm run build

      - name: Fazer upload dos arquivos para o Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v4

        - name: Instalar dependências e fazer o Build
        run: |
          npm install
          npm run build
          cp dist/index.html dist/404.html
